version: '3.4'

services:
  rabbitmq:
    volumes:
      - ./container_data/rabbitmq/lib:/var/lib/rabbitmq
      - ./container_data/rabbitmq/log:/var/log/rabbitmq
    networks:
      - exchangeratemanager_network

  valkey:
    environment:
      - VALKEY_PASSWORD=valkey
    volumes:
      - ./container_data/valkey/dаta:/data
      - ./container_data/valkey/valkey.conf:/etc/valkey/valkey.conf
    networks:
      - exchangeratemanager_network

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./container_data/postgres/data:/var/lib/postgresql/data
    networks:
      - exchangeratemanager_network

  redisinsight:
    container_name: redisinsight
    hostname: redisinsight
    image: redis/redisinsight:latest
    restart: always
    ports:
      - 5540:5540
    user: "1000:1000"
    volumes:
      - ./container_data/valkey/insight_data:/data
    depends_on:
      - valkey
    networks:
      - exchangeratemanager_network

  # exchangeratemanager:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Local
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #   ports:
  #     - "8080"
  #     - "8081"
  #   volumes:
  #     - /var/exchangeratemanager/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - /var/exchangeratemanager/ASP.NET/Https:/home/app/.aspnet/https:ro
  #   networks:
  #     - exchangeratemanager_network

networks:
  exchangeratemanager_network:
